server:
  port: 8080
  servlet:
    context-path: /home

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/QLyKhachSan"
    username: root
    password: 7905
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true